{
    "name": "吧台运营与调酒师工作台",
    "summary": "管理桌台、吧台点单、调酒师任务与实时提成提醒。",
    "version": "1.0.0",
    "category": "Sales/Point of Sale",
    "sequence": 30,
    "author": "多门店项目组",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "hr",
        "product",
        "store_inventory",
        "store_commission",
        "store_finance",
        "store_member",
    ],
    "data": [
        "security/store_bar_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "views/store_bar_table_views.xml",
        "views/store_bar_order_views.xml",
        "views/store_bar_task_views.xml",
        "views/menuitems.xml",
        "data/demo_data.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
}
