{
    "name": "门店会员服务",
    "summary": "扩展会员档案与跨门店互通配置。",
    "version": "1.0.0",
    "category": "Sales",
    "sequence": 40,
    "author": "多门店项目组",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": [
        "contacts",
        "mail",
        "brand_core",
        "portal",
    ],
    "data": [
        "security/store_member_security.xml",
        "security/ir.model.access.csv",
        "data/member_recharge_sequence.xml",
        "views/res_partner_views.xml",
        "views/member_balance_views.xml",
        "views/wizards/phone_bind_wizard_views.xml",
        "views/menu_member.xml",
        "views/portal_templates.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
}
