{
    "name": "众筹与品牌洞察",
    "summary": "管理门店众筹项目、投资流程与分红执行，提供品牌方洞察报表。",
    "version": "1.0.0",
    "category": "Sales",
    "sequence": 60,
    "author": "多门店项目组",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": [
        "mail",
        "brand_core",
        "store_member",
        "portal",
        "board",
    ],
    "data": [
        "security/store_crowdfunding_security.xml",
        "security/ir.model.access.csv",
        "data/crowdfunding_sequence.xml",
        "data/crowdfunding_dashboard_board.xml",
        "views/crowdfunding_investment_views.xml",
        "views/crowdfunding_dividend_views.xml",
        "views/crowdfunding_project_views.xml",
        "views/res_partner_views.xml",
        "views/crowdfunding_portal_templates.xml",
        "reports/crowdfunding_dividend_report.xml",
        "views/crowdfunding_menu.xml",
    ],
    "demo": [
        "demo/crowdfunding_demo.xml",
    ],
    "installable": True,
    "application": True,
}
